project:
  type: website
  output-dir: docs

website:
  title: "MFC Jamboree"
  page-navigation: true

  navbar:
    background: primary
    right:
      - text: "MFC CDT"
        href: https://www.mfccdt.ac.uk/
      - icon: github
        href: https://github.com/mfc-cdt/mfc-jamboree-2026

format:
  html:
    theme: 
      - website-styles.scss
      - cosmo